# Generated by Django 4.2 on 2023-05-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_tasks_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
